// Auto-extracted from index.html GAMES array
// [slug, name, description, category, theme]
export const GAMES = [
  ["stack-tower-game","Stack Tower","Stack blocks as high as you can. Time your taps to align each block and build the tallest tower.","arcade","default"],
  ["zigzag-dash","Zigzag Dash","Navigate through zigzag paths at high speed. Quick reflexes are key to survival.","action","neon"],
  ["aqua-shrink","Aqua Shrink","Dodge rising walls in shrinking aquatic pools. Survive the squeeze.","action","ocean"],
  ["ash-flight","Ash Flight","Soar through volcanic ash clouds, dodging falling debris at increasing speeds.","action","fire"],
  ["ash-hopper","Ash Hopper","Hop across glowing ash platforms as they crumble beneath your feet.","arcade","fire"],
  ["ash-pile","Ash Pile","Stack falling ash blocks into a steady tower before the volcano erupts.","arcade","fire"],
  ["astro-glide","Astro Glide","Glide through asteroid fields, collecting stardust while avoiding collisions.","action","space"],
  ["astro-split","Astro Split","Split your spaceship to dodge dual obstacle streams in deep space.","arcade","space"],
  ["bark-rush","Bark Rush","Rush through a forest, leaping over bark obstacles and fallen logs at high speed.","action","forest"],
  ["beam-shift","Beam Shift","Shift between laser beams in a neon grid. One wrong move ends it all.","action","neon"],
  ["beam-sprint","Beam Sprint","Sprint along shifting energy beams, jumping gaps before they disappear.","action","neon"],
  ["beat-breaker","Beat Breaker","Break rhythmic blocks to the beat. Match the tempo to score big.","rhythm","rhythm"],
  ["beat-chase","Beat Chase","Chase the beat — tap in rhythm as the tempo accelerates and patterns multiply.","rhythm","rhythm"],
  ["block-bouncer","Block Bouncer","Bounce blocks off platforms in a chain reaction. Clear the board to win.","arcade","default"],
  ["block-racer","Block Racer","Race colored blocks down a track, switching lanes to avoid crashes.","action","neon"],
  ["branch-sprint","Branch Sprint","Sprint across tree branches at treetop speed, leaping gaps and swinging on vines.","action","forest"],
  ["bubble-break","Bubble Break","Pop bubbles in the right order before they float away. Speed counts.","arcade","ocean"],
  ["bubble-glide","Bubble Glide","Glide through a stream of bubbles, collecting the right colors while avoiding others.","action","ocean"],
  ["bubble-merge","Bubble Merge","Merge matching bubbles to score points as the board fills up. Think fast.","puzzle","ocean"],
  ["cactus-clash","Cactus Clash","Clash against flying cacti in the desert sun. Dodge, weave, and survive.","action","desert"],
  ["cactus-glide","Cactus Glide","Glide over a cactus field with shrinking hover-power. Land softly or burst.","action","desert"],
  ["candy-shrink","Candy Shrink","A candy world is shrinking! Jump platforms before they melt away.","arcade","candy"],
  ["candy-split","Candy Split","Split candy streams to match colors as they pour faster and faster.","puzzle","candy"],
  ["canopy-rush","Canopy Rush","Leap between towering trees and catch random powerups for extra jumps.","action","forest"],
  ["circle-drift","Circle Drift","Drift a circle along a winding path, never touching the walls.","action","default"],
  ["circuit-coil","Circuit Coil","Coil through electric circuits, completing loops before the power cuts out.","puzzle","neon"],
  ["cloud-match","Cloud Match","Match cloud shapes as they drift by. Faster rounds, harder matches.","puzzle","default"],
  ["cloud-shift","Cloud Shift","Shift between cloud platforms as they move and vanish in the sky.","action","default"],
  ["cog-climb","Cog Climb","Climb a tower of turning cogs without getting crushed by the gears.","arcade","default"],
  ["color-dash","Color Dash","Run through color gates matching your current color. Tap to switch. Speed increases every 10 points.","action","neon"],
  ["color-grove","Color Grove","Navigate a colorful grove, painting your path and matching hues.","puzzle","forest"],
  ["coral-droplet","Coral Droplet","Drop through coral reefs, collecting ocean gems while avoiding sea creatures.","action","ocean"],
  ["cosmic-chain","Cosmic Chain","Swipe to link planets in a chain as obstacles spawn and multiply rapidly.","puzzle","space"],
  ["cosmo-sprint","Cosmo Sprint","Sprint through a cosmos of floating rocks and stars at light speed.","action","space"],
  ["crater-twist","Crater Twist","Twist through crater mazes on an alien planet, avoiding lava pits.","action","fire"],
  ["cube-catch","Cube Catch","Catch falling cubes on a rotating platform. Miss one and it's over.","arcade","default"],
  ["cube-drift","Cube Drift","Drift a cube along narrow floating paths over a vast void. Don't fall.","action","default"],
  ["current-spin","Current Spin","Spin with ocean currents, riding waves and avoiding underwater hazards.","action","ocean"],
  ["dot-drift","Dot Drift","Drift a dot through a maze of moving obstacles without touching the walls.","action","neon"],
  ["dot-sprint","Dot Sprint","Sprint a glowing dot along a path that shifts and narrows without warning.","action","neon"],
  ["dual-drift","Dual Drift","Control two objects simultaneously drifting through mirrored obstacle courses.","action","default"],
  ["dune-climber","Dune Climber","Climb shifting sand dunes that crumble under your weight. Reach the top.","action","desert"],
  ["dune-spinner","Dune Spinner","Spin across desert dunes, building momentum to fly over massive gaps.","action","desert"],
  ["dusk-dart","Dusk Dart","Dart through a twilight sky, dodging birds and clouds at sunset speed.","action","default"],
  ["dusk-dash","Dusk Dash","Dash through the fading light as obstacles multiply with the setting sun.","action","default"],
  ["dusk-defense","Dusk Defense","Defend your base at dusk as waves of enemies close in from all sides.","action","default"],
  ["dusk-drift","Dusk Drift","Drift through a moody dusk landscape, collecting fireflies before dark falls.","action","default"],
  ["dusk-pulse","Dusk Pulse","Pulse through dusk energy waves, syncing your rhythm to the fading light.","rhythm","rhythm"],
  ["echo-drift","Echo Drift","Drift through echoing caverns where walls appear and disappear with sound.","action","rhythm"],
  ["echo-flap","Echo Flap","Flap upward through an echo chamber, riding sound waves to stay aloft.","arcade","rhythm"],
  ["echo-spin","Echo Spin","Spin through concentric sound rings, hitting the right notes to advance.","rhythm","rhythm"],
  ["flip-fathom","Flip Fathom","Flip gravity and plunge through deep ocean layers, avoiding sea life.","action","ocean"],
  ["flip-vines","Flip Vines","Flip between vine paths in the jungle, matching the color of each vine.","action","forest"],
  ["frostfall-stack","Frostfall Stack","Stack icy blocks as they fall faster in a snowstorm. Keep the tower balanced.","arcade","ice"],
  ["frost-flap","Frost Flap","Flap through a frozen tundra, riding icy gusts to stay airborne.","arcade","ice"],
  ["frost-flip","Frost Flip","Flip gravity in a frost world — the floor becomes the ceiling in an instant.","action","ice"],
  ["frost-split","Frost Split","Split icy beams to clear a path through a glacier cave system.","puzzle","ice"],
  ["galaxy-fuse","Galaxy Fuse","Fuse stars together to create supernovas. Chain reactions score massive points.","puzzle","space"],
  ["gear-glide","Gear Glide","Glide across spinning gear platforms, timing your jumps perfectly.","action","default"],
  ["gear-pong","Gear Pong","Bounce a ball between clockwork gears in a steampunk twist on classic pong.","arcade","default"],
  ["gear-rhythm","Gear Rhythm","Tap matching gears on a rotating clockwork wheel as speed escalates.","rhythm","rhythm"],
  ["geo-flux","Geo Flux","Navigate geometric shapes through a shifting flux field that warps reality.","action","default"],
  ["glacier-escape","Glacier Escape","Escape a collapsing glacier — jump between ice blocks before they sink.","action","ice"],
  ["glacier-glide","Glacier Glide","Glide across a glacier surface, gaining speed on downhill runs.","action","ice"],
  ["glide-catch","Glide Catch","Glide through the air, catching falling objects on a shrinking landing zone.","arcade","default"],
  ["glitch-beam","Glitch Beam","Navigate glitching laser beams in a corrupted digital world. Timing is all.","action","neon"],
  ["glitch-sprint","Glitch Sprint","Sprint through a glitching world where the ground disappears without warning.","action","neon"],
  ["glow-beam","Glow Beam","Ride a glowing beam of light, collecting energy orbs before the beam fades.","action","neon"],
  ["glow-divide","Glow Divide","Divide glowing particles into matching groups before the screen overflows.","puzzle","neon"],
  ["glow-drift","Glow Drift","Drift a glowing orb through dark passages, lighting the way forward.","action","neon"],
  ["glow-drop","Glow Drop","Drop glowing balls into the right slots in this fast-paced puzzle game.","puzzle","neon"],
  ["glow-escape","Glow Escape","Escape a glowing maze that reconfigures every time you approach the exit.","action","neon"],
  ["glow-glide","Glow Glide","Glide on streams of neon light, avoiding obstacles in a luminous world.","action","neon"],
  ["gravity-canopy","Gravity Canopy","Navigate a forest canopy where gravity shifts randomly. Hold on tight.","action","forest"],
  ["gravity-chain","Gravity Chain","Chain gravity-affected objects to create platforms and pathways.","puzzle","default"],
  ["gravity-flip","Gravity Flip","Tap to flip gravity up/down while dodging obstacles from both sides. Collect stars for bonus points.","action","space"],
  ["gravity-loop","Gravity Loop","Loop through gravity wells, using their pull to slingshot past obstacles.","action","space"],
  ["gravity-veil","Gravity Veil","Pierce through gravitational veils in space, collecting energy behind each barrier.","action","space"],
  ["gum-pop","Gum Pop","Pop gum bubbles in the correct sequence before they stick to the screen.","arcade","candy"],
  ["hexa-twist","Hexa Twist","Twist hexagonal grids to align colors in this fast-paced spatial puzzle.","puzzle","default"],
  ["hue-walk","Hue Walk","Walk a path that shifts hue — match your color to pass each segment.","puzzle","neon"],
  ["icebound-rush","Icebound Rush","Rush across a frozen tundra while ice platforms crack beneath you.","action","ice"],
  ["jelly-jam","Jelly Jam","Jam jelly blocks together to match flavors before the jar overflows.","puzzle","candy"],
  ["jungle-burst","Jungle Burst","Burst through jungle walls at high speed, smashing obstacles in your path.","action","forest"],
  ["jungle-juggle","Jungle Juggle","Juggle fruit in the jungle canopy, keeping multiple balls in the air.","arcade","forest"],
  ["jungle-link","Jungle Link","Link jungle creatures in a chain to create combos for massive points.","puzzle","forest"],
  ["jungle-orbit","Jungle Orbit","Orbit around jungle trees, swinging to each one before your energy runs out.","action","forest"],
  ["jungle-sprint","Jungle Sprint","Sprint through a dense jungle, leaping obstacles and sliding under vines.","action","forest"],
  ["lava-bloom","Lava Bloom","Bloom through lava fields, collecting rare fire flowers before they wilt.","action","fire"],
  ["lava-catch","Lava Catch","Catch glowing lava drops in a bucket that shrinks with each miss.","arcade","fire"],
  ["lava-leap","Lava Leap","Leap between erupting lava rocks as the floor melts away beneath you.","action","fire"],
  ["lava-rush","Lava Rush","Rush through a volcanic corridor as lava walls close in from both sides.","action","fire"],
  ["lava-splitter","Lava Splitter","Split streams of lava to protect your base from the volcanic flood.","action","fire"],
  ["lava-sprint","Lava Sprint","Dodge multiplying volcanic rocks in an endless blazing lava run.","action","fire"],
  ["leaf-pyramid","Leaf Pyramid","Build a pyramid of falling leaves, stacking them before the wind blows them away.","arcade","forest"],
  ["lollipop-flip","Lollipop Flip","Flip lollipops to match their flavors in a sugary, fast-paced matching game.","arcade","candy"],
  ["lollipop-leap","Lollipop Leap","Leap between giant lollipops as they spin and melt. Collect candy along the way.","action","candy"],
  ["lollipop-loop","Lollipop Loop","Loop the lollipop through spiral candy tracks without touching the edges.","action","candy"],
  ["magma-beat","Magma Beat","Beat rhythms on magma drums as the lava rises. Stay on tempo to survive.","rhythm","fire"],
  ["magma-drift","Magma Drift","Drift a magma ball through underground tunnels without touching the walls.","action","fire"],
  ["magma-link","Magma Link","Link magma nodes together to channel heat and power through volcanic vents.","puzzle","fire"],
  ["magma-pulse","Magma Pulse","Pulse energy through magma channels in sync with seismic waves.","rhythm","fire"],
  ["magma-shift","Magma Shift","Shift between magma streams in a volcanic chamber. One wrong move is fatal.","action","fire"],
  ["magnet-glow","Magnet Glow","Use magnetic forces to attract glowing orbs while repelling obstacles.","puzzle","neon"],
  ["magnetic-cumulus","Magnetic Cumulus","Navigate storm clouds magnetically, attracting lightning bolts and raindrops.","action","default"],
  ["magnet-maze","Magnet Maze","Navigate a maze using magnetic attraction and repulsion to guide your path.","puzzle","default"],
  ["magnet-melt","Magnet Melt","Melt metallic barriers using focused magnetic heat beams to clear the path.","puzzle","default"],
  ["mini-drop","Mini Drop","Drop miniature objects into targets that shrink with every successful hit.","arcade","default"],
  ["molten-spin","Molten Spin","Spin through molten rock chambers, staying on the platform as it shrinks.","action","fire"],
  ["molten-tower","Molten Tower","Build a tower with molten blocks before they solidify. Stack them fast.","arcade","fire"],
  ["moss-merge","Moss Merge","Merge moss patches together to cover the ground before it dries out.","puzzle","forest"],
  ["mushroom-pulse","Mushroom Pulse","Pulse between mushrooms in sync with forest rhythms. Miss a beat and fall.","rhythm","forest"],
  ["narrow-trace","Narrow Trace","Trace a path through increasingly narrow corridors without touching the walls.","action","default"],
  ["nebula-swipe","Nebula Swipe","Swipe through nebula clouds to collect star matter before the void expands.","action","space"],
  ["neon-bounce","Neon Bounce","Bounce a glowing ball between neon platforms. Platforms get narrower as your score increases.","arcade","neon"],
  ["neon-coil","Neon Coil","Coil a neon wire through electrified obstacles without shorting the circuit.","puzzle","neon"],
  ["nimbus-path","Nimbus Path","Follow the nimbus cloud path through storm systems, collecting rain as you go.","action","default"],
  ["oasis-combo","Oasis Combo","Combo-chain water droplets in the desert to keep your oasis alive.","puzzle","desert"],
  ["oasis-hop","Oasis Hop","Hop between oasis pools in the desert as they shrink under the blazing sun.","action","desert"],
  ["orbit-drift","Orbit Drift","Drift in orbit around a planet, avoiding space debris and satellites.","action","space"],
  ["orbit-fade","Orbit Fade","Fade between orbital paths before your signal disappears into deep space.","action","space"],
  ["orbit-flip","Orbit Flip","Flip your orbiting craft to switch between two parallel orbital rings.","action","space"],
  ["orbit-leap","Orbit Leap","Leap between planetary orbits, using gravitational assists to travel further.","action","space"],
  ["orbit-roots","Orbit Roots","Root your orbit in planetary gravity wells, swinging between celestial bodies.","puzzle","space"],
  ["orbit-shift","Orbit Shift","Shift orbital paths to avoid collisions as space traffic intensifies.","action","space"],
  ["orbit-spiral","Orbit Spiral","Spiral inward through planetary rings, collecting fuel before hitting the core.","action","space"],
  ["orbit-stack","Orbit Stack","Stack orbiting satellites in perfect formation before the window closes.","arcade","space"],
  ["pipe-align","Pipe Align","Align pipe segments to create a flow path before the pressure blows.","puzzle","default"],
  ["pixel-coil","Pixel Coil","Coil pixel segments into a growing snake without colliding with yourself.","arcade","pixel"],
  ["pixel-drift","Pixel Drift","Drift pixel blocks through a digital maze in retro 8-bit style.","action","pixel"],
  ["pixel-plunge","Pixel Plunge","Plunge through pixel layers in a retro platformer with old-school charm.","action","pixel"],
  ["pixel-pulse","Pixel Pulse","Pulse through a pixelated world, matching frequencies to open each gate.","rhythm","pixel"],
  ["pixel-soar","Pixel Soar","Soar through 8-bit skies, dodging retro obstacles at increasing speed.","action","pixel"],
  ["pixel-surge","Pixel Surge","Surge through a pixel storm, collecting power-ups while avoiding corruption.","action","pixel"],
  ["polar-bounce","Polar Bounce","Bounce across polar ice caps, avoiding cracks and obstacles.","arcade","ice"],
  ["polar-glide","Polar Glide","Glide across frozen polar surfaces, gaining speed on ice and losing it on snow.","action","ice"],
  ["prism-drift","Prism Drift","Drift through a prism of light, splitting colors to unlock hidden paths.","action","neon"],
  ["prism-rise","Prism Rise","Rise through a prism tower, collecting each color of the rainbow in order.","action","neon"],
  ["pulse-bound","Pulse Bound","Bound to the pulse — jump only when the beat hits to clear obstacles.","rhythm","rhythm"],
  ["pulse-chase","Pulse Chase","Chase the pulse through neon corridors as it accelerates and splits.","rhythm","rhythm"],
  ["pulse-collector","Pulse Collector","Collect energy pulses before they dissipate in this fast-paced arcade game.","arcade","rhythm"],
  ["pulse-flicker","Pulse Flicker","Flicker between pulse frequencies to stay visible in an unstable dimension.","rhythm","rhythm"],
  ["pulse-glide","Pulse Glide","Glide on energy pulses, riding waves of sound through electric skies.","action","rhythm"],
  ["pulse-grove","Pulse Grove","Navigate a bio-electric grove that pulses with energy. Stay in sync.","rhythm","forest"],
  ["pulse-orbit","Pulse Orbit","Orbit in sync with a pulsing star, collecting energy without getting burned.","rhythm","space"],
  ["pulse-path","Pulse Path","Follow the pulsing path through a maze that changes with every heartbeat.","rhythm","rhythm"],
  ["pulse-slide","Pulse Slide","Slide along energy pulse waves, timing your moves to the rhythm.","rhythm","rhythm"],
  ["pulse-split","Pulse Split","Split energy pulses into channels to power different systems simultaneously.","puzzle","rhythm"],
  ["pulse-swing","Pulse Swing","Swing to the pulse — time your arc to the beat for maximum distance.","rhythm","rhythm"],
  ["pulse-trace","Pulse Trace","Trace pulse patterns in the correct sequence before the signal fades.","rhythm","rhythm"],
  ["reef-rush","Reef Rush","Rush through a coral reef, dodging sea creatures and collecting ocean gems.","action","ocean"],
  ["retro-rebound","Retro Rebound","Rebound a ball in retro style, breaking blocks in a classic arcade revival.","arcade","pixel"],
  ["root-roll","Root Roll","Roll through root systems underground, collecting nutrients before they dry up.","action","forest"],
  ["root-rush","Root Rush","Rush through tangled root mazes, finding the exit before time runs out.","action","forest"],
  ["sand-surge","Sand Surge","Surge through desert sandstorms, using the wind to propel yourself forward.","action","desert"],
  ["sandsync-spin","Sandsync Spin","Spin in sync with sand vortexes, matching their rotation to pass through safely.","rhythm","desert"],
  ["shape-rally","Shape Rally","Rally shapes together, matching pairs before the screen overflows.","puzzle","default"],
  ["shape-surge","Shape Surge","Surge through a field of geometric shapes, collecting matching ones for combos.","action","default"],
  ["shrinking-vines","Shrinking Vines","Swing on vines that shrink over time. Reach the next one before they vanish.","action","forest"],
  ["shrink-link","Shrink Link","Link shrinking objects together before they disappear from the screen.","puzzle","default"],
  ["slide-flux","Slide Flux","Slide through flux zones where physics change unpredictably.","action","neon"],
  ["spin-warp","Spin Warp","Warp through spinning portals, timing your entry to avoid the barriers.","action","space"],
  ["splash-dash","Splash Dash","Dash across water surfaces, collecting splashes before you sink.","action","ocean"],
  ["split-ascent","Split Ascent","Split into two characters and ascend parallel paths simultaneously.","action","default"],
  ["split-ember","Split Ember","Split ember streams to extinguish fires before they spread out of control.","action","fire"],
  ["split-snacker","Split Snacker","Split your snacker to collect food from two lanes at the same time.","arcade","default"],
  ["steampile-spin","Steampile Spin","Stack quirky steampunk contraptions as the entire screen rotates unpredictably.","arcade","default"],
  ["steam-pulse","Steam Pulse","Pulse steam through pipes in sync with the boiler rhythm to power the engine.","puzzle","default"],
  ["steam-spin","Steam Spin","Spin steam turbines at the right speed to generate power without overheating.","puzzle","default"],
  ["sugar-rush","Sugar Rush","Rush through a candy world collecting sweet treats before the sugar crash hits.","action","candy"],
  ["sugar-slide","Sugar Slide","Slide across sugary surfaces that melt as you move. Reach the exit fast.","action","candy"],
  ["sunset-collector","Sunset Collector","Collect the colors of the sunset before night falls and the colors fade.","arcade","default"],
  ["sunset-drift","Sunset Drift","Drift through a sunset sky, riding thermal currents and collecting light.","action","default"],
  ["sunset-hopper","Sunset Hopper","Hop across sunset cloud platforms as they dissolve in the evening light.","arcade","default"],
  ["sunset-leap","Sunset Leap","Leap between silhouetted platforms against a stunning sunset backdrop.","action","default"],
  ["sunset-scoop","Sunset Scoop","Scoop up sunset colors in a bucket game that gets harder as the sky darkens.","arcade","default"],
  ["sweet-pulse","Sweet Pulse","Pulse sweet energy through candy circuits in this confectionery adventure.","rhythm","candy"],
  ["sweet-serve","Sweet Serve","Serve sweet treats to customers in a fast-paced restaurant rush game.","arcade","candy"],
  ["sweet-swap","Sweet Swap","Swap sweets to match three in a row in this candy-matching puzzle game.","puzzle","candy"],
  ["sweet-sway","Sweet Sway","Sway between sweet hanging platforms, timing your swings to collect candy.","action","candy"],
  ["swing-drift","Swing Drift","Drift on a swing through obstacle courses, using momentum to dodge hazards.","action","default"],
  ["swing-nebula","Swing Nebula","Swing through a nebula on cosmic vines, collecting star matter.","action","space"],
  ["swing-rush","Swing Rush","Rush across platforms by swinging on ropes at high speed.","action","default"],
  ["swing-shift","Swing Shift","Shift your swing angle in mid-air to change direction and avoid obstacles.","action","default"],
  ["synth-catch","Synth Catch","Catch synthesized music notes as they rain down in this rhythmic arcade game.","arcade","rhythm"],
  ["synth-glide","Synth Glide","Glide through a synthwave world on electronic currents of light.","action","neon"],
  ["synth-shots","Synth Shots","Shoot synthesizer pulses at incoming enemies in this musical shooter.","action","rhythm"],
  ["tide-loop","Tide Loop","Loop through ocean tide patterns, riding waves without being pulled under.","action","ocean"],
  ["tide-tap","Tide Tap","Tap the tide — match wave patterns to surf safely to shore.","rhythm","ocean"],
  ["tide-titan","Tide Titan","Battle as the tide titan, growing stronger with each wave you conquer.","action","ocean"],
  ["tide-twins","Tide Twins","Control twin surfers riding the tide simultaneously on mirrored wave paths.","action","ocean"],
  ["tide-twist","Tide Twist","Bounce to reverse gravity and connect ocean creatures of matching colors during tidal flows.","puzzle","ocean"],
  ["time-mirage","Time Mirage","Navigate through time mirages that duplicate reality with slight delays.","action","space"],
  ["time-tether","Time Tether","Tether to time anchors, rewinding segments to solve temporal puzzles.","puzzle","space"],
  ["trail-runner","Trail Runner","Run an endless trail, jumping obstacles and collecting power-ups.","action","forest"],
  ["trail-tally","Trail Tally","Tally your trail score by collecting markers along a winding mountain path.","action","forest"],
  ["trap-trek","Trap Trek","Trek through a field of traps, timing your steps carefully to survive.","action","default"],
  ["tribal-loop","Tribal Loop","Loop through tribal patterns, following the rhythm of ancient drums.","rhythm","rhythm"],
  ["turbo-cog","Turbo Cog","Tap to toggle direction along a narrow, spinning cog path before your time expires.","action","default"],
  ["turbo-tether","Turbo Tether","Tether to turbo boost pads and slingshot through obstacle courses.","action","default"],
  ["twig-break","Twig Break","Break twigs to create platforms before your character falls into the abyss.","puzzle","forest"],
  ["twig-magnet","Twig Magnet","Use magnetic twigs to attract and repel obstacles in this nature-themed puzzler.","puzzle","forest"],
  ["twilight-tap","Twilight Tap","Tap with the twilight rhythm, matching firefly patterns as night falls.","rhythm","default"],
  ["twin-glow","Twin Glow","Control twin glowing orbs, guiding both to their targets simultaneously.","puzzle","neon"],
  ["twin-leap","Twin Leap","Leap as twin characters in sync, solving platforming puzzles with coordination.","action","default"],
  ["twin-trails","Twin Trails","Navigate twin trails simultaneously, collecting items on both paths at once.","action","default"],
  ["twix-twist","Twix Twist","Twist through double-layered corridors in this sweet arcade adventure.","action","candy"],
  ["valve-flux","Valve Flux","Adjust valves to control flux pressure in this engineering puzzle game.","puzzle","default"],
  ["vine-blur","Vine Blur","Swing rapidly between vines, avoiding multiplying logs and spikes.","action","forest"],
  ["vine-switch","Vine Switch","Swipe to flip gravity while swinging on jungle vines that change colors instantly.","action","forest"],
  ["vine-vault","Vine Vault","Vault over obstacles using vines as springboards in the jungle.","action","forest"],
  ["wave-chain","Wave Chain","Tap to chain oceanic dots while the screen rotates in sync with rolling waves.","puzzle","ocean"],
  ["wave-connect","Wave Connect","Swipe to link dots as gravity randomly changes directions in a vaporwave cityscape.","puzzle","ocean"],
  ["wave-flicker","Wave Flicker","Flicker between wave frequencies to stay in phase with the oscillating world.","action","ocean"],
  ["zoom-drift","Zoom Drift","Drift at zoom speed through a neon tunnel, avoiding walls as speed increases.","action","neon"],
  ["zoom-orb","Zoom Orb","Zoom an orb through a gauntlet, collecting rings before the timer expires.","arcade","neon"],
  ["zoom-pong","Zoom Pong","Pong at zoom speed — the ball gets faster with every successful hit.","arcade","neon"],
];
